const pages={overview:"Overview",edge:"Edge Network",analytics:"Analytics",jobs:"Scrape Jobs",logs:"Request Logs",api:"API & Webhooks",ai:"Titan AI",billing:"Billing & Usage"};
const $=id=>document.getElementById(id), toast=$("toast");
let currentUser=null, currentProfile=null, secretVisible=false;
const getToken=()=>sessionStorage.getItem("titanJwt");
function showToast(msg){toast.textContent=msg;toast.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove("show"),3200)}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(getToken()?{Authorization:`Bearer ${getToken()}`}:{}) ,...(options.headers||{})};const r=await fetch(path,{...options,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}

document.querySelectorAll(".nav button").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(btn.dataset.page)?.classList.add("active");$("pageTitle").textContent=pages[btn.dataset.page]||btn.dataset.page;$("sidebar").classList.remove("open")}));
$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");

// Cosmetic telemetry remains visual; account usage below is real backend data.
const chart=$("chart"); if(chart){for(let i=0;i<20;i++){const b=document.createElement("div");b.className="bar";b.style.height=(18+Math.random()*50)+"%";chart.appendChild(b)}}
let engine=false,timer=null;
function setEngine(on){engine=on;$("engineBtn").classList.toggle("on",on);$("engineText").textContent=on?"ENGINE ONLINE":"ENGINE OFFLINE";$("telemetryState").textContent=on?"Live telemetry running":"Engine stopped";$("scraperStatus").textContent=on?"READY":"STANDBY";if(timer)clearInterval(timer);if(on)timer=setInterval(()=>{if($("rps"))$("rps").textContent=Math.floor(3000+Math.random()*1500).toLocaleString();if($("latency"))$("latency").textContent=Math.floor(35+Math.random()*25)+" ms"},700)}
$("engineBtn").onclick=()=>setEngine(!engine);
$("pingBtn").onclick=async()=>{try{const d=await api("/api/health");showToast(`API ${d.status} • DB ${d.database}`)}catch(e){showToast(e.message)}};

const authModal=$("authModal"),profileModal=$("profileModal"); let authMode="signup";
function syncAuthTabs(){const up=authMode==="signup";$("signupTab").classList.toggle("primary",up);$("signinTab").classList.toggle("primary",!up);$("authTitle").textContent=up?"Create TitanCDN account":"Sign in to TitanCDN";$("authSubmit").textContent=up?"CREATE ACCOUNT":"SIGN IN";$("authName").style.display=up?"block":"none";$("authCompany").style.display="none"}
function openAuth(mode="signup"){authMode=mode;syncAuthTabs();authModal.classList.add("show")}
$("authBtn").onclick=()=>openAuth("signup");$("signupTab").onclick=()=>{authMode="signup";syncAuthTabs()};$("signinTab").onclick=()=>{authMode="signin";syncAuthTabs()};
authModal.onclick=e=>{if(e.target===authModal)authModal.classList.remove("show")};profileModal.onclick=e=>{if(e.target===profileModal)profileModal.classList.remove("show")};
function renderSignedOut(){currentUser=currentProfile=null;$("profileBtn").hidden=true;$("authBtn").hidden=false;if($("apiSignedOut"))$("apiSignedOut").hidden=false;if($("apiSignedIn"))$("apiSignedIn").hidden=true;if($("freePlanBanner"))$("freePlanBanner").style.display="none";renderUsage(null)}
function renderUser(u){currentUser=u;$("authBtn").hidden=true;$("profileBtn").hidden=false;$("profileName").textContent=u.username||"Titan User";$("avatar").textContent=(u.username||"T")[0].toUpperCase();if($("apiSignedOut"))$("apiSignedOut").hidden=true;if($("apiSignedIn"))$("apiSignedIn").hidden=false;if($("freePlanBanner"))$("freePlanBanner").style.display=u.plan==="free"?"block":"none"}
function fmt(n){return Number(n||0).toLocaleString("en-US")}
function planName(p){return ({free:"FREE",pro:"PRO DEVELOPER",business:"BUSINESS CORE",enterprise:"ENTERPRISE TITAN"}[p]||String(p||"free").toUpperCase())}
function renderUsage(profile){const u=profile?.usage;if(!u){$("usageUsed").textContent="—";$("usageSummary").textContent="Sign in to see your monthly usage";$("usagePlan").textContent="—";$("usageRemaining").textContent="—";$("usageReset").textContent="—";$("usageBar").style.setProperty("--w","0%");return}const pct=Math.min(100,(u.used/u.limit)*100||0);$("usageUsed").textContent=fmt(u.used);$("usageSummary").textContent=`requests used of ${fmt(u.limit)}`;$("usagePlan").textContent=planName(profile.plan);$("usageRemaining").textContent=fmt(u.remaining);$("usageReset").textContent=new Date(u.resetAt).toLocaleDateString();$("usageBar").style.setProperty("--w",pct+"%");if($("freeUsed"))$("freeUsed").textContent=fmt(u.used);if($("freeRemaining"))$("freeRemaining").textContent=fmt(u.remaining)}
async function loadProfile(){const d=await api("/api/profile");currentProfile=d.user;renderUser(d.user);renderUsage(d.user);return d.user}
$("authSubmit").onclick=async()=>{const username=$("authName").value.trim(),email=$("authEmail").value.trim(),password=$("authPassword").value;try{if(!email||!password)throw new Error("Email and password are required");if(authMode==="signup"){if(!$("terms").checked)throw new Error("Accept Terms and Privacy Policy");const created=await api("/api/auth/register",{method:"POST",body:JSON.stringify({username:username||email.split("@")[0],email,password,clientId:freeClientId()})});const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})});sessionStorage.setItem("titanJwt",d.token);authModal.classList.remove("show");await loadProfile();await loadKeys();showToast(created.message||"Безплатният план е активиран • 100,000 заявки");if($("freeWelcomeModal"))$("freeWelcomeModal").classList.add("show");return}const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})});sessionStorage.setItem("titanJwt",d.token);authModal.classList.remove("show");await loadProfile();await loadKeys();showToast("Signed in • your plan is active")}catch(e){showToast(e.message)}};
$("profileBtn").onclick=async()=>{try{const p=await loadProfile();$("pName").value=p.username;$("pEmail").value=p.email;$("profilePlan").textContent=planName(p.plan);$("profileUsageText").textContent=`${fmt(p.usage.used)} / ${fmt(p.usage.limit)} requests`;$("profileRemaining").textContent=fmt(p.usage.remaining);$("profileReset").textContent=new Date(p.usage.resetAt).toLocaleDateString();$("profileApiStatus").textContent=p.usage.blocked?"QUOTA REACHED":"ACTIVE";$("profileApiStatus").className=p.usage.blocked?"red":"green";$("profileUsageBar").style.setProperty("--w",Math.min(100,p.usage.used/p.usage.limit*100)+"%");profileModal.classList.add("show")}catch(e){showToast(e.message)}};
$("logoutBtn").onclick=()=>{sessionStorage.removeItem("titanJwt");sessionStorage.removeItem("titanApiKey");profileModal.classList.remove("show");$("apiKey").value="No API key loaded";renderSignedOut();showToast("Signed out")};
async function restoreSession(){if(!getToken()){renderSignedOut();return}try{await loadProfile();await loadKeys()}catch{sessionStorage.removeItem("titanJwt");renderSignedOut()}}

async function loadKeys(){if(!getToken())return;const d=await api("/api/keys");const active=(d.keys||[]).find(k=>!k.revokedAt);currentKeyMeta=active||null;const raw=sessionStorage.getItem("titanApiKey");if(raw)$("apiKey").value=raw.slice(0,22)+"••••••••••••";else if(active)$("apiKey").value=active.prefix+"••••••••••••";else $("apiKey").value="No API key — click CREATE KEY";if(active){$("apiAiInput").value=active.extractionInstructions||"";$("apiKeyProfile").textContent=active.extractionMode==="custom"?`CUSTOM • ${active.extractionInstructions}`:"ALL AVAILABLE DATA"}else{$("apiKeyProfile").textContent="Not configured yet"}}
let keySetupTimer=null,keySetupSeconds=10,keySetupTouched=false,keySetupCreating=false;
function closeKeySetup(){clearInterval(keySetupTimer);$("keySetupModal").classList.remove("show")}
async function createConfiguredKey(){if(keySetupCreating)return;keySetupCreating=true;clearInterval(keySetupTimer);try{const instructions=$("keySetupInput").value.trim();$("keySetupCreate").disabled=true;$("keySetupCreate").textContent="CREATING...";const d=await api("/api/keys",{method:"POST",body:JSON.stringify({name:"Dashboard Key",extractionInstructions:instructions})});sessionStorage.setItem("titanApiKey",d.key.value);currentKeyMeta=d.key;secretVisible=true;$("apiKey").value=d.key.value;$("revealKey").textContent="HIDE";$("rotateKey").textContent="CREATE NEW";$("apiKeyProfile").textContent=instructions?`CUSTOM • ${instructions}`:"ALL AVAILABLE DATA";closeKeySetup();showToast(instructions?"API key created with custom AI extraction":"API key created • ALL AVAILABLE DATA mode")}catch(e){showToast(e.message)}finally{keySetupCreating=false;$("keySetupCreate").disabled=false;$("keySetupCreate").textContent="CONFIRM & CREATE KEY"}}
function openKeySetup(){if(!getToken()){showToast("Sign in first");return}keySetupTouched=false;keySetupSeconds=10;$("keySetupInput").value="";$("keySetupCountdown").textContent="10";$("keySetupModal").classList.add("show");clearInterval(keySetupTimer);keySetupTimer=setInterval(()=>{if(keySetupTouched)return;keySetupSeconds--;$("keySetupCountdown").textContent=String(Math.max(0,keySetupSeconds));if(keySetupSeconds<=0)createConfiguredKey()},1000)}
$("keySetupInput").addEventListener("focus",()=>{keySetupTouched=true;clearInterval(keySetupTimer);$("keySetupStatus").textContent="Timer paused — finish your instruction, then confirm."});
$("keySetupInput").addEventListener("input",()=>{keySetupTouched=true;clearInterval(keySetupTimer);$("keySetupStatus").textContent="Custom extraction instruction will be saved to this API key."});
$("keySetupCreate").onclick=createConfiguredKey;$("keySetupCancel").onclick=closeKeySetup;$("keySetupModal").onclick=e=>{if(e.target===$("keySetupModal"))closeKeySetup()};
$("rotateKey").onclick=openKeySetup;
$("revealKey").onclick=()=>{const raw=sessionStorage.getItem("titanApiKey");if(!raw){showToast("Full key is available only in the browser session where it was created");return}secretVisible=!secretVisible;$("apiKey").value=secretVisible?raw:raw.slice(0,22)+"••••••••••••";$("revealKey").textContent=secretVisible?"HIDE":"REVEAL"};

function addLog(url,status){const root=$("logTable");const row=document.createElement("div");row.className="logrow";row.innerHTML=`<b>${new Date().toLocaleTimeString()}</b><span class="${status<300?'green':'red'}">${status}</span><span>${new URL(url).hostname}</span><span>API</span><span>GET</span>`;root.prepend(row)}
$("sendBtn").onclick=async()=>{const url=$("targetUrl").value.trim(),format=$("format").value,out=$("preview"),key=sessionStorage.getItem("titanApiKey");try{if(!getToken())throw new Error("Sign in first");if(!key)throw new Error("Create a new API key first. Full keys cannot be recovered later.");new URL(url);out.textContent="Fetching public target and processing extraction...";$("scraperStatus").textContent="RUNNING";const r=await fetch("/api/v1/scrape",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":key},body:JSON.stringify({targetUrl:url,outputFormat:format})});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);out.textContent=JSON.stringify(d,null,2);addLog(url,d.responseCode||200);$("scraperStatus").textContent="READY";await loadProfile();showToast("Extraction completed using this API key profile")}catch(e){out.textContent=JSON.stringify({success:false,error:e.message},null,2);$("scraperStatus").textContent="ERROR";showToast(e.message)}};
$("askAi").onclick=()=>{const q=$("aiInput").value.trim();if(!q)return;$("extractInstructions").value=q;$("aiOut").textContent="Instruction loaded into Developer Workbench: "+q;document.querySelector('[data-page="overview"]').click();showToast("AI instruction loaded")};
$("createJob").onclick=()=>document.querySelector('[data-page="overview"]').click();
if($("apiSignupBtn"))$("apiSignupBtn").onclick=()=>openAuth("signup");
if($("apiAiUse"))$("apiAiUse").onclick=async()=>{try{if(!currentKeyMeta)throw new Error("Create an API key first");const q=$("apiAiInput").value.trim();const d=await api(`/api/keys/${encodeURIComponent(currentKeyMeta.id)}/profile`,{method:"PATCH",body:JSON.stringify({extractionInstructions:q})});currentKeyMeta={...currentKeyMeta,...d.key};$("apiKeyProfile").textContent=q?`CUSTOM • ${q}`:"ALL AVAILABLE DATA";showToast(q?"Titan AI profile saved to this API key":"API key set to ALL AVAILABLE DATA")}catch(e){showToast(e.message)}};

document.querySelectorAll(".buy").forEach(btn=>btn.onclick=async()=>{try{if(!getToken())return openAuth("signup");btn.disabled=true;const d=await api("/api/billing/checkout",{method:"POST",body:JSON.stringify({plan:btn.dataset.plan})});location.href=d.checkoutUrl}catch(e){showToast(e.message)}finally{btn.disabled=false}});
$("modalClose").onclick=()=>$("modal").classList.remove("show");$("modalAction").onclick=()=>$("modal").classList.remove("show");
if($("freeWelcomeClose"))$("freeWelcomeClose").onclick=()=>$("freeWelcomeModal").classList.remove("show");
restoreSession();
